
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ALEX
 */
public class convertText2Morse extends javax.swing.JFrame {

    private String ps_abcTexto;
    private String ps_equivalentes[];
    
    /**
     * Creates new form convertText2Morse
     */
    public convertText2Morse() {
        initComponents();
        inicializa();        // configuramos la ventana
        configurarVentana();        // configuramos la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("TEXTO NATURAL");

        jButton3.setText("CONVERTIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRADUCTOR");

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField1.setToolTipText("");
        jTextField1.setName("i_texto"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("TEXTO NATURAL. Escriba el texto que desea traducri a código Morse");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("CÓDIGO MORSE. Escriba el código morse que desea traducir a texto natural");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/abc_morse.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/abc_texto.JPG"))); // NOI18N

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CONVERTIR");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CONVERTIR");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/traducir.jpg"))); // NOI18N

        jLabel8.setText("https://www.traductormorse.com/");

        jLabel9.setText("Puede comprobar en la siguiente página:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)))
                .addGap(56, 56, 56)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:

        //jTextField2.setText(jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        
        //Validate characters
        char ls_char;
        int li_ascii;
        try {
            ls_char = evt.getKeyChar();
            li_ascii = Character.toString((char) ls_char).codePointAt(0);
        } catch (Exception err1) {
            li_ascii = 0;
        }
        //JOptionPane.showMessageDialog(null, "li_ascii: " + li_ascii, "Error", JOptionPane.ERROR_MESSAGE);
        
        if (li_ascii > 90) {
            evt.consume();
        } else if ((li_ascii < 48) && (li_ascii != 32)) {
            evt.consume();
        } else if ((li_ascii > 57) && (li_ascii < 65)) {
            evt.consume();
        }

        //Set a MaxLimit
        String ls_text = jTextField1.getText();
        int length = ls_text.length();
        if (length == 20) {
            evt.consume();
        } else if (length > 20) {
            // show your error message
            JOptionPane.showMessageDialog(null, "Error. No se permiten mas de 20 caracteres: ", "Restricción", JOptionPane.ERROR_MESSAGE);
            jTextField1.setText(ls_text.substring(0, 20));
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //MORSE TO TEXTO
        String ls_morse = jTextField2.getText();
        
        if (ls_morse.length() > 0) {
            String ls_char;
            String ls_texto = "";
            String ls_charMorse = "";
            int li_pos = 0;
            int li_index;
            int li_count_espacios = 0;
            boolean lb_continuar = false;

            try {
                while (li_pos < ls_morse.length()) {
                    ls_char = ls_morse.substring(li_pos, (li_pos + 1));
                    //Validacion de espacios
                    if (ls_char.equals(" ")) {
                        if (lb_continuar && (0 == li_count_espacios)) {
                            //buscar charMorse
                            li_index = 0;
                            while (li_index < 36) {
                                if (ls_charMorse.equals(ps_equivalentes[li_index])) {
                                    ls_texto += ps_abcTexto.substring(li_index, (li_index + 1));
                                    li_index = 35;
                                }
                                li_index++;
                            }
                            ls_charMorse = "";//Afuera, si no la encuentra, no se limpia
                        } else if (lb_continuar && (2 == li_count_espacios)) {
                            ls_texto += " ";
                        }
                        li_count_espacios++;
                    } else {
                        ls_charMorse += ls_char;
                        lb_continuar = true;
                        li_count_espacios = 0;
                    }
                    li_pos++;
                }
                if (lb_continuar && (0 == li_count_espacios) && (ls_charMorse.length() > 0)) {
                    //Tomando el ultimo caracter
                    li_index = 0;
                    while (li_index < 36) {
                        if (ls_charMorse.equals(ps_equivalentes[li_index])) {
                            ls_texto += ps_abcTexto.substring(li_index, (li_index + 1));
                            li_index = 35;
                        }
                        li_index++;
                    }
                }
            } catch (Exception err1) {
                ls_texto = "ERROR: " + err1.toString();
            }

            if (ls_texto.length() == 0) {
                ls_texto = "Cadena no valida";
            }
            jTextField1.setText(ls_texto);
        }        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //TEXTO TO MORSE
        String ls_texto = jTextField1.getText();
        
        if (ls_texto.length() > 0) {
            String ls_char;
            String ls_morse = "";
            int li_pos = 0;
            int li_index;
            int li_count_espacios = 0;
            boolean lb_continuar = false;

            try {
                while (li_pos < ls_texto.length()) {
                    ls_char = ls_texto.substring(li_pos, (li_pos + 1));
                    //Validacion de espacios
                    if (ls_char.equals(" ")) {
                        if (lb_continuar && (0 == li_count_espacios)) {
                            ls_morse += "  ";
                            li_count_espacios++;
                        }
                    } else {
                        li_index = ps_abcTexto.indexOf(ls_char);
                        ls_morse += ps_equivalentes[li_index] + " ";
                        lb_continuar = true;
                        li_count_espacios = 0;
                    }
                    li_pos++;
                }
            } catch (Exception err1) {
                ls_morse = "ERROR: " + err1.toString();
            }

            jTextField2.setText(ls_morse);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        //Validate characters
        char ls_char;
        int li_ascii;
        try {
            ls_char = evt.getKeyChar();
            li_ascii = Character.toString((char) ls_char).codePointAt(0);
        } catch (Exception err1) {
            li_ascii = 0;
        }
        //JOptionPane.showMessageDialog(null, "li_ascii: " + li_ascii, "Error", JOptionPane.ERROR_MESSAGE);
        //En codigo morse, solo espacio, punto y guion
        if ((li_ascii != 45) && (li_ascii != 46) && (li_ascii != 32)) {
            evt.consume();
        }

        //Set a MaxLimit: 200
        String ls_text = jTextField2.getText();
        int length = ls_text.length();
        if (length == 200) {
            evt.consume();
        } else if (length > 200) {
            // show your error message
            JOptionPane.showMessageDialog(null, "Error. No se permiten mas de 200 caracteres: ", "Restricción", JOptionPane.ERROR_MESSAGE);
            jTextField2.setText(ls_text.substring(0, 20));
        }        
    }//GEN-LAST:event_jTextField2KeyTyped

    private void inicializa() {
        ps_abcTexto = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        ps_equivalentes = new String[37];
        
        ps_equivalentes[0] = ".-";    //A
        ps_equivalentes[1] = "-...";  //B
        ps_equivalentes[2] = "-.-.";  //C
        ps_equivalentes[3] = "-..";   //D
        ps_equivalentes[4] = ".";     //E
        ps_equivalentes[5] = "..-.";  //F
        ps_equivalentes[6] = "--.";   //G
        ps_equivalentes[7] = "....";  //H
        ps_equivalentes[8] = "..";    //I
        ps_equivalentes[9] = ".---";  //J
        ps_equivalentes[10] = "-.-";  //K
        ps_equivalentes[11] = ".-.."; //L
        ps_equivalentes[12] = "--";   //M
        ps_equivalentes[13] = "-.";   //N
        ps_equivalentes[14] = "---";  //O
        ps_equivalentes[15] = ".--."; //P
        ps_equivalentes[16] = "--.-"; //Q
        ps_equivalentes[17] = ".-.";  //R
        ps_equivalentes[18] = "...";  //S
        ps_equivalentes[19] = "-";    //T
        ps_equivalentes[20] = "..-";  //U
        ps_equivalentes[21] = "...-"; //V
        ps_equivalentes[22] = ".--";  //W
        ps_equivalentes[23] = "-..-"; //X
        ps_equivalentes[24] = "-.--"; //Y
        ps_equivalentes[25] = "--.."; //Z
        ps_equivalentes[26] = ".----";//1
        ps_equivalentes[27] = "..---";//2
        ps_equivalentes[28] = "...--";//3
        ps_equivalentes[29] = "....-";//4
        ps_equivalentes[30] = ".....";//5
        ps_equivalentes[31] = "-....";//6
        ps_equivalentes[32] = "--...";//7
        ps_equivalentes[33] = "---..";//8
        ps_equivalentes[34] = "----.";//9
        ps_equivalentes[35] = "-----";//0
    }
    
    private void configurarVentana() {
        this.setTitle("TRADUCTOR A CÓDIGO MORSE");              // colocamos titulo a la ventana
        this.setLocationRelativeTo(null);                       // centramos la ventana en la pantalla
        this.setLayout(null);                                   // no usamos ningun layout, solo asi podremos dar posiciones a los componentes
        this.setResizable(false);                               // hacemos que la ventana no sea redimiensionable
        getContentPane().setBackground(Color.WHITE);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);    // hacemos que cuando se cierre la ventana termina todo proceso        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convertText2Morse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convertText2Morse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convertText2Morse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convertText2Morse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convertText2Morse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
